AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"
    - "lib/generators/**/*"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': "[]"
    '%W': "[]"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StructInheritance:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Documentation:
  Enabled: false # TODO: Enable again once we have more docs
